### ISSUE TITLE
Plugin not working on Windows 10

### ISSUE THREAD

**Issue by patschl** [memflow/memflow-reclass-plugin#3]
Plugin does not work on a Windows 10 host. ReClass simply does not recognize it as a plugin.

**Comment by ko1N** [comment]
The root cause for this was that ReClass.NET requires some resource fields to be set on Windows.

This can be seen here: https://github.com/ReClassNET/ReClass.NET/blob/93850bf5c40e79f075640ddecc438ee4d109310e/ReClass.NET/Plugins/PluginManager.cs#L72

I added the fields on the current master branch. Can you confirm if it works for you now?

**Comment by patschl** [comment]
Works as intended now! Thanks for the support.
